---
name: Create release

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read version
        id: version
        run: |
          version=$(python setup.py --version)
          echo "version=$version" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1.3.7
        with:
          tag: ${{ env.version }}
      - uses: ncipollo/release-action@v1
